use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use std::collections::HashMap;

/// Represents a canonical Contractor (Golden Record)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Contractor {
    /// Canonical UUID for this contractor (generated by MDM)
    pub id: Uuid,
    /// Normalized Business Name (Razón Social)
    pub name: String,
    /// Primary Legal ID (NIT or Cédula)
    pub legal_id: String,
    /// List of source IDs linked to this canonical record (e.g., from different datasets)
    pub source_ids: Vec<String>,
    /// Metadata about when this record was last updated
    pub last_updated: DateTime<Utc>,
    /// Trust score of this record (0.0 to 1.0)
    pub confidence_score: f32,
}

impl Contractor {
    pub fn new(name: String, legal_id: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            name,
            legal_id,
            source_ids: Vec::new(),
            last_updated: Utc::now(),
            confidence_score: 1.0,
        }
    }
}

/// Represents a Public Entity (Alcaldía, Gobernación, Ministerio, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicEntity {
    pub id: Uuid,
    pub name: String,
    pub nit: String,
    pub category: String, // e.g., "MUNICIPAL", "NACIONAL"
    pub department: Option<String>,
    pub city: Option<String>,
}

/// Represents a Normalized Contract linked to Golden Records
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Contract {
    pub id: Uuid,
    pub source_id: String, // ID from SECOP II
    pub contractor_id: Uuid,
    pub entity_id: Uuid,
    pub description: String, // Objeto del contrato
    pub value_amount: f64,
    pub currency: String,
    pub date_signed: Option<DateTime<Utc>>,
    pub duration_days: Option<i32>,
    pub url: Option<String>,
}
